// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: v1/save-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Editor    string `protobuf:"bytes,2,opt,name=editor,proto3" json:"editor,omitempty"`
	Object    string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *CreateSaveRequest) Reset() {
	*x = CreateSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_save_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaveRequest) ProtoMessage() {}

func (x *CreateSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_save_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaveRequest.ProtoReflect.Descriptor instead.
func (*CreateSaveRequest) Descriptor() ([]byte, []int) {
	return file_v1_save_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSaveRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateSaveRequest) GetEditor() string {
	if x != nil {
		return x.Editor
	}
	return ""
}

func (x *CreateSaveRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type CreateSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaveId string `protobuf:"bytes,1,opt,name=save_id,json=saveId,proto3" json:"save_id,omitempty"`
}

func (x *CreateSaveResponse) Reset() {
	*x = CreateSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_save_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaveResponse) ProtoMessage() {}

func (x *CreateSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_save_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaveResponse.ProtoReflect.Descriptor instead.
func (*CreateSaveResponse) Descriptor() ([]byte, []int) {
	return file_v1_save_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSaveResponse) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

type GetSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *GetSaveRequest) Reset() {
	*x = GetSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_save_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaveRequest) ProtoMessage() {}

func (x *GetSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_save_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaveRequest.ProtoReflect.Descriptor instead.
func (*GetSaveRequest) Descriptor() ([]byte, []int) {
	return file_v1_save_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSaveRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaveId string `protobuf:"bytes,1,opt,name=save_id,json=saveId,proto3" json:"save_id,omitempty"`
	Editor string `protobuf:"bytes,2,opt,name=editor,proto3" json:"editor,omitempty"`
	Object string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *GetSaveResponse) Reset() {
	*x = GetSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_save_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaveResponse) ProtoMessage() {}

func (x *GetSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_save_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaveResponse.ProtoReflect.Descriptor instead.
func (*GetSaveResponse) Descriptor() ([]byte, []int) {
	return file_v1_save_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSaveResponse) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

func (x *GetSaveResponse) GetEditor() string {
	if x != nil {
		return x.Editor
	}
	return ""
}

func (x *GetSaveResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type DeleteSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *DeleteSaveRequest) Reset() {
	*x = DeleteSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_save_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSaveRequest) ProtoMessage() {}

func (x *DeleteSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_save_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSaveRequest.ProtoReflect.Descriptor instead.
func (*DeleteSaveRequest) Descriptor() ([]byte, []int) {
	return file_v1_save_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSaveRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeleteSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *DeleteSaveResponse) Reset() {
	*x = DeleteSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_save_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSaveResponse) ProtoMessage() {}

func (x *DeleteSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_save_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSaveResponse.ProtoReflect.Descriptor instead.
func (*DeleteSaveResponse) Descriptor() ([]byte, []int) {
	return file_v1_save_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSaveResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_v1_save_service_proto protoreflect.FileDescriptor

var file_v1_save_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x31, 0x2f, 0x73, 0x61, 0x76, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x76, 0x31,
	0x22, 0x62, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x22, 0x2d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x61,
	0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x76,
	0x65, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x22, 0x32, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x32, 0xd9, 0x01, 0x0a, 0x0b, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x61,
	0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x12, 0x1a, 0x2e, 0x73,
	0x61, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x76,
	0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_save_service_proto_rawDescOnce sync.Once
	file_v1_save_service_proto_rawDescData = file_v1_save_service_proto_rawDesc
)

func file_v1_save_service_proto_rawDescGZIP() []byte {
	file_v1_save_service_proto_rawDescOnce.Do(func() {
		file_v1_save_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_save_service_proto_rawDescData)
	})
	return file_v1_save_service_proto_rawDescData
}

var file_v1_save_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_save_service_proto_goTypes = []interface{}{
	(*CreateSaveRequest)(nil),  // 0: save.v1.CreateSaveRequest
	(*CreateSaveResponse)(nil), // 1: save.v1.CreateSaveResponse
	(*GetSaveRequest)(nil),     // 2: save.v1.GetSaveRequest
	(*GetSaveResponse)(nil),    // 3: save.v1.GetSaveResponse
	(*DeleteSaveRequest)(nil),  // 4: save.v1.DeleteSaveRequest
	(*DeleteSaveResponse)(nil), // 5: save.v1.DeleteSaveResponse
}
var file_v1_save_service_proto_depIdxs = []int32{
	0, // 0: save.v1.SaveService.CreateSave:input_type -> save.v1.CreateSaveRequest
	2, // 1: save.v1.SaveService.GetSave:input_type -> save.v1.GetSaveRequest
	4, // 2: save.v1.SaveService.DeleteSave:input_type -> save.v1.DeleteSaveRequest
	1, // 3: save.v1.SaveService.CreateSave:output_type -> save.v1.CreateSaveResponse
	3, // 4: save.v1.SaveService.GetSave:output_type -> save.v1.GetSaveResponse
	5, // 5: save.v1.SaveService.DeleteSave:output_type -> save.v1.DeleteSaveResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_save_service_proto_init() }
func file_v1_save_service_proto_init() {
	if File_v1_save_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_save_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_save_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_save_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_save_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_save_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_save_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_save_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_save_service_proto_goTypes,
		DependencyIndexes: file_v1_save_service_proto_depIdxs,
		MessageInfos:      file_v1_save_service_proto_msgTypes,
	}.Build()
	File_v1_save_service_proto = out.File
	file_v1_save_service_proto_rawDesc = nil
	file_v1_save_service_proto_goTypes = nil
	file_v1_save_service_proto_depIdxs = nil
}
