// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: v1/save-service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Save_CreateSave_FullMethodName = "/save.v1.Save/CreateSave"
	Save_GetSave_FullMethodName    = "/save.v1.Save/GetSave"
	Save_DeleteSave_FullMethodName = "/save.v1.Save/DeleteSave"
)

// SaveClient is the client API for Save service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaveClient interface {
	CreateSave(ctx context.Context, in *CreateSaveRequest, opts ...grpc.CallOption) (*CreateSaveResponse, error)
	GetSave(ctx context.Context, in *GetSaveRequest, opts ...grpc.CallOption) (*GetSaveResponse, error)
	DeleteSave(ctx context.Context, in *DeleteSaveRequest, opts ...grpc.CallOption) (*DeleteSaveResponse, error)
}

type saveClient struct {
	cc grpc.ClientConnInterface
}

func NewSaveClient(cc grpc.ClientConnInterface) SaveClient {
	return &saveClient{cc}
}

func (c *saveClient) CreateSave(ctx context.Context, in *CreateSaveRequest, opts ...grpc.CallOption) (*CreateSaveResponse, error) {
	out := new(CreateSaveResponse)
	err := c.cc.Invoke(ctx, Save_CreateSave_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saveClient) GetSave(ctx context.Context, in *GetSaveRequest, opts ...grpc.CallOption) (*GetSaveResponse, error) {
	out := new(GetSaveResponse)
	err := c.cc.Invoke(ctx, Save_GetSave_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saveClient) DeleteSave(ctx context.Context, in *DeleteSaveRequest, opts ...grpc.CallOption) (*DeleteSaveResponse, error) {
	out := new(DeleteSaveResponse)
	err := c.cc.Invoke(ctx, Save_DeleteSave_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaveServer is the server API for Save service.
// All implementations must embed UnimplementedSaveServer
// for forward compatibility
type SaveServer interface {
	CreateSave(context.Context, *CreateSaveRequest) (*CreateSaveResponse, error)
	GetSave(context.Context, *GetSaveRequest) (*GetSaveResponse, error)
	DeleteSave(context.Context, *DeleteSaveRequest) (*DeleteSaveResponse, error)
	mustEmbedUnimplementedSaveServer()
}

// UnimplementedSaveServer must be embedded to have forward compatible implementations.
type UnimplementedSaveServer struct {
}

func (UnimplementedSaveServer) CreateSave(context.Context, *CreateSaveRequest) (*CreateSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSave not implemented")
}
func (UnimplementedSaveServer) GetSave(context.Context, *GetSaveRequest) (*GetSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSave not implemented")
}
func (UnimplementedSaveServer) DeleteSave(context.Context, *DeleteSaveRequest) (*DeleteSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSave not implemented")
}
func (UnimplementedSaveServer) mustEmbedUnimplementedSaveServer() {}

// UnsafeSaveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaveServer will
// result in compilation errors.
type UnsafeSaveServer interface {
	mustEmbedUnimplementedSaveServer()
}

func RegisterSaveServer(s grpc.ServiceRegistrar, srv SaveServer) {
	s.RegisterService(&Save_ServiceDesc, srv)
}

func _Save_CreateSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveServer).CreateSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Save_CreateSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveServer).CreateSave(ctx, req.(*CreateSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Save_GetSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveServer).GetSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Save_GetSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveServer).GetSave(ctx, req.(*GetSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Save_DeleteSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveServer).DeleteSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Save_DeleteSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveServer).DeleteSave(ctx, req.(*DeleteSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Save_ServiceDesc is the grpc.ServiceDesc for Save service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Save_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "save.v1.Save",
	HandlerType: (*SaveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSave",
			Handler:    _Save_CreateSave_Handler,
		},
		{
			MethodName: "GetSave",
			Handler:    _Save_GetSave_Handler,
		},
		{
			MethodName: "DeleteSave",
			Handler:    _Save_DeleteSave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/save-service.proto",
}
