name: Copy service-proto to gateways

on:
  push:
    branches:
      - develop
    paths:
      # ①新しくサービスが増えたらこの部分を追加する
      - 'user-service/api/**'
      - 'member-service/api/**'
      - 'image-service/api/**'
      - 'project-service/api/**'
      - 'token-service/api/**'
      - 'save-service/api/**'
      
jobs:
  collect-diff:
    runs-on: ubuntu-latest
    steps:
      - name: set up github config
        run: |
          git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
          git config --global user.name "${{ secrets.USERNAME_GITHUB }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # ②新しくサービスが増えたらこの部分を追加する
      - name: collect diff
        id: diff
        run: |
          mkdir -p $HOME/service/user-service
          cp -r user-service/api/* $HOME/service/user-service

          mkdir -p $HOME/service/project-service
          cp -r project-service/api/* $HOME/service/project-service

          mkdir -p $HOME/service/member-service
          cp -r member-service/api/* $HOME/service/member-service

          mkdir -p $HOME/service/image-service
          cp -r image-service/api/* $HOME/service/image-service

          mkdir -p $HOME/service/token-service
          cp -r token-service/api/* $HOME/service/token-service
        
          mkdir -p $HOME/service/save-service
          cp -r save-service/api/* $HOME/service/save-service 

      - name: Checkout BFF repository
        uses: actions/checkout@v3
        with:
          repository: schema-creator/graph-gateway
          token: ${{ secrets.GH_PAT }}
          ref: develop
      
      - name: Create a branch when it doesn't exist
        run: |
          branch_is_existing=$(
            git fetch origin ft/wfc-bff &&
            echo true ||
            echo false
          )
          if [ $branch_is_existing = 'false' ]; then
            git switch -c ft/wfc-bff
            git push origin ft/wfc-bff
          else
            echo "branch is existing"
          fi
      
      # $HOMEにコピーしたファイルをコミットする
      - name: copy file to gateways
       
        run: |
          git switch -c ft/copy-file/${{github.sha}}
          cp -r $HOME/service/* pkg/grpc/
      
      - name: commit and push changes
        run: |
          git add .
          git commit -m "feat: copy grpc to graph-gateway"
          git push origin ft/copy-file/${{github.sha}}
      
      - name: create Pull Request to frontend
        run: |
          gh pr create \
            --title ":robot: copy grpc [bot]" \
            --body ":robot: copy grp[bot]" \
            --repo schema-creator/graph-gateway \
            --base ft/wfc-bff \
            --head ft/copy-file/${{github.sha}} \
            --reviewer "${{ github.event.head_commit.committer.username || github.triggering_actor }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}